<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Location\City;
use App\Models\Location\Country;
use Illuminate\Database\Seeder;

class CountryCitySeeder extends Seeder
{
    public function run(): void
    {
        $countries = [
            ['country' => 'Абхазия', 'code' => 'AB', 'city' => 'Сухуми', 'postalcode' => ''],
            ['country' => 'Австралия', 'code' => 'AU', 'city' => 'Мельбурн', 'postalcode' => ''],
            ['country' => 'Австрия', 'code' => 'AT', 'city' => 'Вена', 'postalcode' => ''],
            ['country' => 'Азербайджан', 'code' => 'AZ', 'city' => 'Баку', 'postalcode' => ''],
            ['country' => 'Англия', 'code' => 'GB', 'city' => 'Норвич', 'postalcode' => ''],
            ['country' => 'Армения', 'code' => 'AM', 'city' => 'Ванадзор', 'postalcode' => ''],
            ['country' => 'Армения', 'code' => 'AM', 'city' => 'Ереван', 'postalcode' => ''],
            ['country' => 'Афганистан', 'code' => 'AF', 'city' => 'Кишим', 'postalcode' => ''],
            ['country' => 'Беларусь', 'code' => 'BY', 'city' => 'Минск', 'postalcode' => ''],
            ['country' => 'Великобритания', 'code' => 'GB', 'city' => 'Лондон', 'postalcode' => ''],
            ['country' => 'Венгрия', 'code' => 'HU', 'city' => 'Будапешт', 'postalcode' => ''],
            ['country' => 'Германия', 'code' => 'DE', 'city' => 'Кинзау', 'postalcode' => ''],
            ['country' => 'Германия', 'code' => 'DE', 'city' => 'Мюнхен', 'postalcode' => ''],
            ['country' => 'Грузия', 'code' => 'GE', 'city' => 'Кобулети', 'postalcode' => ''],
            ['country' => 'Грузия', 'code' => 'GE', 'city' => 'Тбилиси', 'postalcode' => ''],
            ['country' => 'Израиль', 'code' => 'IL', 'city' => 'Тельавив', 'postalcode' => ''],
            ['country' => 'Ирландия', 'code' => 'IE', 'city' => 'Дублин', 'postalcode' => ''],
            ['country' => 'Италия', 'code' => 'IT', 'city' => 'Рим', 'postalcode' => ''],
            ['country' => 'Казахстан', 'code' => 'KZ', 'city' => 'Акколь', 'postalcode' => ''],
            ['country' => 'Казахстан', 'code' => 'KZ', 'city' => 'Актау', 'postalcode' => ''],
            ['country' => 'Казахстан', 'code' => 'KZ', 'city' => 'Актобе', 'postalcode' => ''],
            ['country' => 'Казахстан', 'code' => 'KZ', 'city' => 'Алматы', 'postalcode' => ''],
            ['country' => 'Казахстан', 'code' => 'KZ', 'city' => 'Астана', 'postalcode' => ''],
            ['country' => 'Казахстан', 'code' => 'KZ', 'city' => 'Атырау', 'postalcode' => ''],
            ['country' => 'Казахстан', 'code' => 'KZ', 'city' => 'Караганда', 'postalcode' => ''],
            ['country' => 'Казахстан', 'code' => 'KZ', 'city' => 'Кокшетау', 'postalcode' => ''],
            ['country' => 'Казахстан', 'code' => 'KZ', 'city' => 'Костанай', 'postalcode' => ''],
            ['country' => 'Казахстан', 'code' => 'KZ', 'city' => 'Павлодар', 'postalcode' => ''],
            ['country' => 'Казахстан', 'code' => 'KZ', 'city' => 'Семей', 'postalcode' => ''],
            ['country' => 'Казахстан', 'code' => 'KZ', 'city' => 'Талгар', 'postalcode' => ''],
            ['country' => 'Казахстан', 'code' => 'KZ', 'city' => 'Талдыкорган', 'postalcode' => ''],
            ['country' => 'Казахстан', 'code' => 'KZ', 'city' => 'Уральск', 'postalcode' => ''],
            ['country' => 'Казахстан', 'code' => 'KZ', 'city' => 'Усть-Каменогорск', 'postalcode' => ''],
            ['country' => 'Казахстан', 'code' => 'KZ', 'city' => 'Шымкент', 'postalcode' => ''],
            ['country' => 'Канада', 'code' => 'CA', 'city' => 'Торонто', 'postalcode' => ''],
            ['country' => 'Кыргызстан', 'code' => 'KG', 'city' => 'Бишкек', 'postalcode' => ''],
            ['country' => 'Нидерланды', 'code' => 'NL', 'city' => 'Амстердам', 'postalcode' => ''],
            ['country' => 'ОАЭ', 'code' => 'AE', 'city' => 'Дубай', 'postalcode' => ''],
            ['country' => 'Польша', 'code' => 'PL', 'city' => 'Варшава', 'postalcode' => ''],
            ['country' => 'Польша', 'code' => 'PL', 'city' => 'Вроцлав', 'postalcode' => ''],
            ['country' => 'Польша', 'code' => 'PL', 'city' => 'Олава', 'postalcode' => ''],
            ['country' => 'Португалия', 'code' => 'PT', 'city' => 'Порту', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Абакан', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Адлер', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Адыгейск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Азов', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Аксай', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Альметьевск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Анадырь', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Анапа', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Анжеро-Судженск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Артем', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Артемовский', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Архангельск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Астрахань', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'аул Новая Адыгея', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Ахтубинск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Балашиха', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Барнаул', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Белгород', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Бердск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Березники', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Беслан', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Бийск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Билибино', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Бирибиджан', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Благовещенск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Боровичи', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Братск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Брянск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Бугульма', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Бузулук', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Великий Новгород', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Видное', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Владивосток', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Владикавказ', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Владимир', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Волгоград', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Вологда', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Волоколамск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Воркута', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Воронеж', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Всеволожск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Вышний Волочек', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Вязьма', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Гатчина', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Геленджик', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Глазов', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Горячий Ключ', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Дальнегорск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Дзержинск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Дмитров', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Долгопрудный', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Домодедово', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Евпатория', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Ейск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Екатеринбург', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Елец', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Есентуки', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Есипово', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Жешарт', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Жирекен', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Жуковский', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Звенигород', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Зеленогорск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Зеленоград', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Златоозерный', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Златоуст', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Иваново', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Ивантеевка', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Ижевск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Ижора', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Инта', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Иркутск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Истра', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Ишим', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Йошкар-Ола', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Казань', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Калининград', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Калуга', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Камск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Катовище', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Кашира', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Кемерово', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Керчь', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Киров', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Клин', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Коломна', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Колпино', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Комсомольск на Амуре', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Копейск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Королев', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Кострома', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Котельники', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Красногорск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Краснодар', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Красноярск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Кубинка', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Кудрово', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Курган', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Курганск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Курск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Лабытнаги', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Лакинск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Липецк', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Лихославль', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Лобня', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Луга', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Лыткарино', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Любань', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Люберцы', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Магадан', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Магнитогорск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Майкоп', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Махачкала', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Миасс', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Михайловск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Можайск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Москва', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Мурманск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Мытищи', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Набережные Челны', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Надым', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Нальчик', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Нарофоминск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Нарынка', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Нерюнги', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Нефтеюганск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Нижневартовск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Нижнекамск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Нижний Новгород', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Нижний Тагил', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Новокузнецк', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Новопокровская', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Новороссийск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Новосибирск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Ногинск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Норынка', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Ноябрьск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Обнинск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Одинцово', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Октябрьский', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Омск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Орел', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Оренбург', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Орехово-Зуево', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Певек', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Пенза', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Переславль Залесский', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Пермь', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Петрозаводск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Петропавловск Камчатский', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Печора', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Подольск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Пос. Купол', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'пос. Энем', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'пос. Яблоновский', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Псков', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Пушкин', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Пушкино', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Пятигорск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Раменское', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Реутов', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Россошь', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Ростов', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Ростов-на-Дону', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Рубцовск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Рудника Купол', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Рязань', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Салават', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Салехард', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Самара', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Санкт-Петербург', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Саранск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Саратов', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Светогорск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Себеж', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Севастополь', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Североморск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Североуральск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Серпухов', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Сим', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Симферополь', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Смоленск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Советский', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Соликамск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Солнечногорск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Сосновоборск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Сосновый Бор', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Сочи', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Ставрополь', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Старый Оскол', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Сургут', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Сыктывкар', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Таганрог', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Тамбов', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Тверь', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Тихорецк', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Тольятти', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Томск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Тосно', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Туймазы', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Тула', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Тюмень', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Улан-Уде', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Ульяновск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Уссурийск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Усть-Ильинск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Уфа', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Ухта', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Учалы', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Феодосия', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Хабаровск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Хани', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Ханты-Мансийск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Химки', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Хотьково', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Чебоксары', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Челябинск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Череповец', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Черкесск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Чехов', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Чита', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Угольные копи', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Эгвекинот', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Лорино', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Провидения', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Беринговский', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Шахты', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Щекино', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Щелково', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Югра', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Южно-Сахалинск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Юрюзань', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Якутск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Ялта', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Ялутоловск', 'postalcode' => ''],
            ['country' => 'Россия', 'code' => 'RU', 'city' => 'Ярославль', 'postalcode' => ''],
            ['country' => 'Румыния', 'code' => 'RO', 'city' => 'Бухарест', 'postalcode' => ''],
            ['country' => 'Сингапур', 'code' => 'SG', 'city' => 'Сингапур', 'postalcode' => ''],
            ['country' => 'Турция', 'code' => 'TR', 'city' => 'Стамбул', 'postalcode' => ''],
            ['country' => 'Украина', 'code' => 'UA', 'city' => 'Белая Церковь', 'postalcode' => ''],
            ['country' => 'Украина', 'code' => 'UA', 'city' => 'Бровари', 'postalcode' => ''],
            ['country' => 'Украина', 'code' => 'UA', 'city' => 'Винница', 'postalcode' => ''],
            ['country' => 'Украина', 'code' => 'UA', 'city' => 'Днепр', 'postalcode' => ''],
            ['country' => 'Украина', 'code' => 'UA', 'city' => 'Днепропетровск', 'postalcode' => ''],
            ['country' => 'Украина', 'code' => 'UA', 'city' => 'Житомир', 'postalcode' => ''],
            ['country' => 'Украина', 'code' => 'UA', 'city' => 'Запорожье', 'postalcode' => ''],
            ['country' => 'Украина', 'code' => 'UA', 'city' => 'Ивано-Франковск', 'postalcode' => ''],
            ['country' => 'Украина', 'code' => 'UA', 'city' => 'Ирпень', 'postalcode' => ''],
            ['country' => 'Украина', 'code' => 'UA', 'city' => 'Киев', 'postalcode' => ''],
            ['country' => 'Украина', 'code' => 'UA', 'city' => 'Краснощек', 'postalcode' => ''],
            ['country' => 'Украина', 'code' => 'UA', 'city' => 'Луцк', 'postalcode' => ''],
            ['country' => 'Украина', 'code' => 'UA', 'city' => 'Львов', 'postalcode' => ''],
            ['country' => 'Украина', 'code' => 'UA', 'city' => 'Одесса', 'postalcode' => ''],
            ['country' => 'Украина', 'code' => 'UA', 'city' => 'Полтава', 'postalcode' => ''],
            ['country' => 'Украина', 'code' => 'UA', 'city' => 'Прилуки', 'postalcode' => ''],
            ['country' => 'Украина', 'code' => 'UA', 'city' => 'Сумы', 'postalcode' => ''],
            ['country' => 'Украина', 'code' => 'UA', 'city' => 'Тростянец', 'postalcode' => ''],
            ['country' => 'Украина', 'code' => 'UA', 'city' => 'Херсон', 'postalcode' => ''],
            ['country' => 'Украина', 'code' => 'UA', 'city' => 'Хмельницкий', 'postalcode' => ''],
            ['country' => 'Украина', 'code' => 'UA', 'city' => 'Черкассы', 'postalcode' => ''],
            ['country' => 'Украина', 'code' => 'UA', 'city' => 'Чернигов', 'postalcode' => ''],
            ['country' => 'Украина', 'code' => 'UA', 'city' => 'Черновцы', 'postalcode' => ''],
            ['country' => 'Франция', 'code' => 'FR', 'city' => 'Бордо', 'postalcode' => ''],
            ['country' => 'Франция', 'code' => 'FR', 'city' => 'Корсика', 'postalcode' => ''],
            ['country' => 'Франция', 'code' => 'FR', 'city' => 'Маастрихт', 'postalcode' => ''],
            ['country' => 'Чехия', 'code' => 'CZ', 'city' => 'Брно', 'postalcode' => ''],
            ['country' => 'Чехия', 'code' => 'CZ', 'city' => 'Прага', 'postalcode' => ''],
            ['country' => 'Швеция', 'code' => 'SE', 'city' => 'Стокгольм', 'postalcode' => ''],
            ['country' => 'Эстония', 'code' => 'EE', 'city' => 'Рига', 'postalcode' => ''],
            ['country' => 'Япония', 'code' => 'JP', 'city' => 'Токио', 'postalcode' => ''],
        ];

        foreach ($countries as $data) {
            $country = Country::where('name', $data['country'])->first();
            if (!$country) {
                $country = Country::create([
                    'name' => $data['country'],
                    'code' => $data['code']
                ]);
            }
            City::create([
                'name' => $data['city'],
                'country_id' => $country->id
            ]);
        }
    }
}
